package dbo.notifier.services;

public enum EventType {
    DB_SCRAMBLE,
    DOJO_WAR,
    BUDO_KID_SOLO,
    BUDO_KID_TEAM,
    BUDO_ADULT_SOLO,
    BUDO_ADULT_TEAM,
    DOUBLE_XP,
    DOUBLE_RANKED,
    DOUBLE_TOKEN,
    DOUBLE_DB,
    DOUBLE_WAGU,
    DOUBLE_UPGRADE,
    DOUBLE_CRAFTING,
    DOUBLE_GEMSTONE,
    DOUBLE_BOX,
    BEE,
    FAIRY,
    BUNNY,
    SUMMER,
    CHRISTMAS,
    HALLOWEEN,
    APRIL_FOOL
}
